[package]
name = "kit-storage"
version = "0.1.0"
authors = ["zhangzhankui <zzk13180@gmail.com>"]
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"